version: '3.8'

services:
  nextjs:
    container_name: nextjs
    build: .
    ports:
      - '3000:3000'
    volumes:
      - ./app:/frontend/app
      - ./tests:/frontend/tests
    command: npm run dev